language: python
sudo: false
env:
  matrix:

  globals:

python:
  - "2.7"
  - "3.5"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script:
  - python manage.py test
  # runs coverage
  - coverage run manage.py test
  - coverage xml
  - python-codacy-coverage -r coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov