language: python
sudo: false
env:
  matrix: 
  globals: 

python:
- '3.5'

install: pip install -r requirements.txt

script:
- python manage.py test
- python-codacy-coverage -r coverage.xml
- codecov

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: Fyl5HEf/ba+R5AdLpFDzi6WKQjFdItlGFNMjE6+AnDqvsjpb34tbMhQz0ZAH6CTIcXpJCEwmFlNcqX1tfQuE1SSVa0giSvFP5YYec5rZmHrra+33/Nbe9BPkO/XJZPf9sefH4fU/hNQsowQ9rLJrs+pShQ+xCbeZlUCvCBy4pJZTURf5LI3qU+E5v6NWvErl3LDjy+d0eJ0Jh42sQf4QCuhri4ZiHHhxPDKcAHiPNuY0WYDSoTA9AcnzjPAu0WaJMjVIUcbIX7ExcYns9nlHNbk9ty85k2mjPvGjgfwOGQgPk/yG0qRQieVdR4ccBL8+W9KeUxPrjKUoCihbggut7DPQlVBNdU8JfxUTtXgatTJFRzgIKejSs5XwyhcH6S1r6kiIti2Qu/VOJDH4ZDN4Npp5g+ImglxsewqlUE5rjn71mW/xyF6a3X2L9JwQauLjtjStVWdl8kc9r8oUgvOlg3D4z1Isvp/+Sud2sB8OVqvaDbXUsQypG2MvUebT2FiRPtzlKLA1VhYBwOjJcCvrkqRtva6rxYDnC10u6J92ry1s85LGIicrxDE3DVreFbZ+kHeitap82qVbVp18hE4A9wvEgJVD1ftmUZbaCShUryxGJVh/bczIDZJi3xmKE83l29yIJZzoJ2F0dQpBJfJSz8DI8KsjONiK/pHiSPXvrag=
    app: hadithi
    on:
      branch: master
      python: 3.5.1

